# -*- coding: utf-8 -*-
"""basic_if_else1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h37yYBF6H7GrrDVeIN1-Ho7ijGm9q8k0

Q1 Write a program that takes an integer input from the user and checks whether the number is odd or
even.

Q2 Write a program that takes three numbers as input and prints the largest of the three.

Q3 Write a program to check if a given year is a leap year. A leap year is divisible by 4 but not by 100
unless it is also divisible by 400.

Q4 Write a program that takes a percentage (integer) as input and
prints the corresponding grade based
on the following criteria:
>= 90: Grade A
>= 80: Grade B
>= 70: Grade C
>= 60: Grade D
< 60: Grade F

Q5 Write a program that checks if a given letter is a vowel (a, e, i, o, u) or a consonant.

Q6 Write a basic calculator program that takes two numbers and an operator (+, -, *, /) as input and
performs the specified operation. Print the result based on the operation.

Q7 Write a program that takes a number as input and checks whether it is positive, negative, or zero.

Q8 Write a program that checks if a username and password entered by the user match the pre-set values
username = "admin" and password = "1234". If both match, print "Login Successful", otherwise print
"Login Failed".

Q9 Write a program that takes three sides of a triangle as input and checks if those sides form a valid
triangle. A triangle is valid if the sum of any two sides is greater than the third side.
Check conditions like a + b > c, b + c > a, and a + c > b.

Q10 Write a program that calculates the Body Mass Index (BMI) based on user input for weight (in
kilograms) and height (in meters). Then categorize the BMI into:
Underweight (BMI < 18.5)
Normal weight (18.5 <= BMI < 24.9)
Overweight (25 <= BMI < 29.9)
Obesity (BMI >= 30)
Use the formula: BMI = weight / (height ** 2)

Q11 Write a program that calculates the discount for a product based on its price:
If price is greater than 1000, discount is 10%
If price is between 500 and 1000, discount is 5%
Otherwise, no discount
Print the final price after applying the discount.

Q12 Write a program that takes the name of a month as input and prints the number of days in that
month. Consider leap years for February.

Q13 Write a program that simulates a simple ATM. The user should be able to:
Check balance
Deposit money
Withdraw money (ensure the balance doesn't go negative) Use an if-else structure to handle the user's
choices.

Q14 Write a program that categorizes a given age into different groups:
Infant (0-1 year)
Toddler (2-4 years)
Child (5-12 years)
Teenager (13-19 years)
Adult (20-59 years)
Senior (60 years and above)

Q15 Write a program that takes an integer (1-7) as input and prints the corresponding day of the week (1
for Monday, 2 for Tuesday, etc.).
"""

#Q1
num=int(input("Enter the number :"))
if (num%2==0):
  print("even")
else:
  print("odd")

#Q2
a=int(input("Enter the number 1:"))
b=int(input("Enter the number 2:"))
c=int(input("Enter the number 3:"))
if (a<b and a<c):
  print("smaller is A")
elif (b<a and b<c):
  print("smaller is B")
elif (c<b and c<a):
  print("smaller is c")

#Q3
year=int(input("Enter the year :"))
if (year%100==0):
  print("NOT leap year")
elif(year%4==0):
  print("leap year")
else:
  print("NOT leap year")

#Q4
percentage=int(input("Enter the percentage :"))
if(percentage>=90):
  print("grade A")
elif(percentage>=80):
  print("grade B")
elif(percentage>=70):
  print("grade C")
elif(percentage>=60):
  print("grade D")
elif(percentage<60):
  print("grade f")

#Q5
letter = input("Enter a letter: ")

char = letter.lower()
if char in ['a', 'e', 'i', 'o', 'u']:
    print(f"{char} is a vowel.")
elif char.isalpha():
    print(f"{char} is a consonant.")
else:
    print("Invalid input. Please enter an alphabet letter.")

#Q6
a=int(input("Enter the number 1:"))
b=int(input("Enter the number 2:"))
opr=input("Enter the operator:")
if(opr=="+"):
  res=a+b
elif(opr=="-"):
  res=a-b
elif(opr=="*"):
  res=a*b
elif(opr=="/"):
  res=a/b
print(res)

#Q7
a=int(input("Enter the number 1:"))
if(a>0):
  print(" positive")
elif(a<0):
  print("negative")
else:
  print("neutral")

#Q8
user_name=input("Enter username: ")
user_passw=input("Enter password: ")
if (user_name=="admin" and1 user_passw=="1234"):
  print("login succesfull")
else:
  print("login Failed")

#Q9
a=int(input("Enter the side 1:"))
b=int(input("Enter the side 2:"))
c=int(input("Enter the side 3:"))
if(a + b > c and b + c > a and a + c > b):
  print("valid triangle")
else:
  print("invalid triangle")

#Q10
weight=int(input("enter the weight(in kilograms)"))
height=float(input("enter the height(in meters) "))

bmi= weight/(height**2)
if (bmi<18.5):
  print("underweight")
elif (bmi<24.9):
  print("normal weight")
elif (bmi<29.9):
  print("overweight")
elif (bmi>=30):
  print("obesity")
print(bmi)

#Q11
price=int(input("Enter the price"))
if price>1000:
  price=price*0.9
elif price>500:
  price=price*0.95
else:
  price=price
print("price: ",price)

#Q12
month = input("Enter the name of the month: ").lower()

if month == 'january' or month == 'march' or month == 'may' or month == 'july' or month == 'august' or month == 'october' or month == 'december':
    print("31 days")
elif month == 'april' or month == 'june' or month == 'september' or month == 'november':
    print("30 days")
elif month == 'february':
        print("29 days")

#Q13
net_amount=10000
while True:
  query=input("do you want to quit, deposit or withdrawal:").lower()
  if query=="deposit":
    amount=int(input("Enter the amount to be deposited :"))
    net_amount=net_amount+amount
    print(f"amount is deposited {amount} and current balance {net_amount}")

  elif query=="withdrawal":
    amount=int(input("Enter the amount to be withdraw :"))
    net_amount=net_amount+amount
    print(f"amount is withdraw {amount} and current balance {net_amount}")

  elif query=="quit":
    break

  else:
    print("Enter the correct input")

#Q14
age = int(input("Enter the age: "))

if age >= 0 and age <= 1:
    print("Infant")
elif age >= 2 and age <= 4:
    print("Toddler")
elif age >= 5 and age <= 12:
    print("Child")
elif age >= 13 and age <= 19:
    print("Teenager")
elif age >= 20 and age <= 59:
    print("Adult")
elif age >= 60:
    print("Senior")
else:
    print("Invalid age")

#Q15
day = int(input("Enter a number (1-7): "))

if day == 1:
    print("Monday")
elif day == 2:
    print("Tuesday")
elif day == 3:
    print("Wednesday")
elif day == 4:
    print("Thursday")
elif day == 5:
    print("Friday")
elif day == 6:
    print("Saturday")
elif day == 7:
    print("Sunday")
else:
    print("Invalid input")

